### ISSUE TITLE
White bar appearing in the app

### ISSUE THREAD

**Issue by HarshitGupta29** [imadsyed333/WordListReactNative#1]
![image](https://user-images.githubusercontent.com/47056611/176839471-eaf77686-aa67-4581-9d64-70be0a7071c3.png)
Why tf is a white bar there ???? I want this solved asap

**Comment by imadsyed333** [comment]
I will be pushing a fix shortly. Stay tuned.

**Comment by imadsyed333** [comment]
Fixed in WordList 5.1.0
